### ISSUE TITLE
GitHub repos page: URL on top is incorrect (need help to update)

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/r-base-parallel#3]
The 'Website' URL part of Description/Website on top of the GitHub repos page https://github.com/rocker-org/r-parallel/ is incorrect.

@cboettig @eddelbuettel, can you please update it to: https://hub.docker.com/r/rocker/r-parallel

**Comment by eddelbuettel** [comment]
Done, thanks for the pointer.
