### ISSUE TITLE
Docker page: Overview info needs to be updated (I lack permission)

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/r-base-parallel#4]
Hi @cboettig @eddelbuettel, the Overview page on https://hub.docker.com/r/rocker/r-parallel needs to be updated.  Would it be possible if I get permission to do that myself because I can imagine it'll have to be updated on a regular basis.

**Comment by eddelbuettel** [comment]
That's usually a straight up copy (or rather: 'read from' as not distinct 'copy' is made) of the README.md at GH.  You can write to that, no?

**Comment by HenrikBengtsson** [comment]
With offline help from @eddelbuettel, I think it now works.
