### ISSUE TITLE
Docker Hub: How do I trigger rebuilds, add new tags, ...?

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/r-base-parallel#5]
@cboettig @eddelbuettel, am I missing sufficient permissions on Docker Hub https://hub.docker.com/r/rocker/r-parallel/?  I cannot really do anything there.  Specifically, I cannot trigger new builds.  When I go to the https://cloud.docker.com/repository/docker/rocker/r-parallel/builds page, it's all empty for me.

**Comment by eddelbuettel** [comment]
Before this escalates, could we take this off-line?   Three issue tickets in three minutes by the same person in the same repo usually signals something or someone is not quite right.

**Comment by HenrikBengtsson** [comment]
Seems to work now.  Thanks for your offline help @eddelbuettel.

It looks like I should skip the Docker Hub webpage for orchestrating things, and instead use the `docker` CLI for things such as tags, etc.
